travis:
  secure:
    BINSTAR_TOKEN: T3yxsOAHY/NLoS7tEwoq4veeralb2GIhpkrYB+pwFu54VCW2C5OD1y9dTmrsByPIjaO8yog++E+G1jrUtySKGo0a744VaPectM5TQGcdR/XixZteG40kcd8wzJiIA9QkskUaIVVbRHEWIqh2yKRO1Ze0R0QFUHW8GHKZ8/rXrIMQ+Ohx9udeHs0mBE62maqSUQEdo/pHQAuTjKa5iaqbihSRWT19m3b35cyGWQmh5ubkSvHrlNGBMHmx7uXMtPUzqaIKGdkzXR3q08GpepE6esNAb6kP/6Jo6y2hB7Ls4CiIL4LafNQ6I4aWTQdo3YLBTBS8MERnsyDdH40vmMtXsIzZUiwaeg4zwzzNlC7S+uUvGb7iVPNbhk/5IwKI/jdZggDBBMWYBZ95SUpfXhWK8hxOuAaJS8b2WfSq1xCz+5O3jCNcZsckRZdfoNt0Hv/nUO0pGT+A9L7HUeTLTmPVlLY0iPcqHeHgV7WH8uJU69wDigNOq7GxrTBlUrMQTTjhN9dEQGsPQqqWSfkNT8EunhOIUmYrQaHGAn4pRra1DuA7GN/lMm8zo1XN3Pkii3KHYbPEq02dYV6hwJUG23QNAXf6H7M9xZzPcPsGCvYMPcr0/2lKd7cIvJYx9mH0ttz8FlwIaiZTxCmpC0o1h5jilpM6b+4Ua3HPa/KEhQVMC8A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
