travis:
  secure:
    BINSTAR_TOKEN: qKGCsWgi6qFuu5Lrxsy4fRLoQwFyIGEcjtCJpybsnzcNC5+CbylZAu/O9PURN051Zy6RigNbE/hfU2ytwYf6mhuWb6NMvwWtyrlfdrIX/l58MebUo+lrD+KiIWMz8rCOVvYuIHIwhXMBED7Lh49nZAL10E+Q+/JMxqAM2YmTLKyoWeH+pXe6sOqAkp9MYLPL0UXm54sP4GAPaRlLUaf5bfV5aGM+kuuX1ofQ3yYRBTQmaoDo3WPtKpbgbpUOT0ChHF9uIxIObn27+VTD44gytTYNp8/UjEMLnv90CAA0gzPOiEH9VWZWw038c99KlfbrGUh3NDPgKEp3w31VdPNKalpWc0SfdIkJhTgbBUL5WN9/IroOEpC6/lwmSSSkr/zkqxfBTos/aTlyaMq5OKgjYlrz17wG8cElSJNauWMq9bXbzqdqDGIneWUomhpb1hSISWRpLtHnhphdlnUFNlh9n1gPEAm+W53BRzfw4s2J5Tei4ohegGlDDGtQzAJanpuV+zBoZ6CrqOiS28Yp+1FfAapoOOOMX18K5rrlqJHGBNyvoU4DqrUHaq9/Rm4v0IQYlxAb4JH7blDyFx8FfzQF69Uwxy81Z4qiHnqXBNLqb5/4gp0rDVNEIcQI3xtUnW2JnrDFNc5wWFpKHUzAA7rwnaDLGui9nEv2ZhbfME0FJmQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
